- route:
    id: "FisToNrlms"
    from: "csp:{{resources.ibm.mq.channels.csp.request-queue}}"
    steps:
      - to:
          uri: "nrlms:{{resources.ibm.mq.channels.nrlms.request-queue}}"
      - process:
          ref: "billingProcessor"
      - to:
          uri: "kafka:{{resources.kafka.topicName}}?brokers={{resources.kafka.brokers}}"

- route:
    id: "NrlmsToFis"
    from: "nrlms:{{resources.ibm.mq.channels.nrlms.response-queue}}"
    steps:
      - to:
          uri: "csp:{{resources.ibm.mq.channels.csp.response-queue}}"