spring:
  config:
    import: queues-docker.yml

application:
  camel:
    demo-routes-autostartup: true

resources:
  ibm.mq.fis:
    hostname: localhost
    port: 1414
    queue-manager: QMMSKT09
    channel: DEV.APP.SVRCONN
  ibm.mq.nrlms:
    hostname: localhost
    port: 1414
    queue-manager: QMMSKT09
    channel: DEV.APP.SVRCONN

  kafka:
    brokers: 127.0.0.1:9092
    topicName: super-topic

  activemq:
    broker-url: tcp://localhost:61616