resources:
  ibm.mq:
    hostname: s-msk-t-imq011.raiffeisen.ru
    port: 1414
    queue-manager: QMMSKT03
    channels:
      csp:
        channel: CSP.MSKT03
        request-queue: INT.FIS.CSP.REQ
        response-queue: INT.FIS.CSP.RESP
      nrlms:
        channel: NRLMS.MSKT03
        request-queue: INT.CSP.NRLMS.REQ
        response-queue: INT.CSP.NRLMS.RESP