resources:
  # todo track https://jira.raiffeisen.ru/browse/MQAPI-446 for connection settings
  ibm.mq:
    hostname: localhost
    port: 1414
    queue-manager: QMMSKT09
    channel: DEV.APP.SVRCONN
    csp.request-queue: INT.FIS.CSP.REQ
    csp.response-queue: INT.FIS.CSP.RESP
    nrlms.request-queue: INT.CSP.NRLMS.REQ
    nrlms.response-queue: INT.CSP.NRLMS.RESP