spring:
  profiles:
    active: docker

# Camel app name
camel:
  springboot:
    name: CSP API Manager
    routes-include-pattern: classpath:routes/*

# how often to trigger the timer
timer.period: 2000

# expose actuator endpoint via HTTP
management:
  endpoints:
    web.exposure.include: info,health,camelroutes
    # turn on actuator health check
    health.enabled: true

    # allow to obtain basic information about camel routes (read only mode)
    camelroutes:
      enabled: true
      read-only: true
