resources:
  ibm.mq:
    hostname: localhost
    port: 1414
    queue-manager: QMMSKT09
    channels:
      csp:
        channel: DEV.APP.SVRCONN
        request-queue: DEV.QUEUE.1
        response-queue: DEV.QUEUE.2
      nrlms:
        channel: DEV.APP.SVRCONN
        request-queue: DEV.QUEUE.2
        response-queue: DEV.QUEUE.3