resources:
  some-system:
    ibm.mq:
      # todo list dev environment resources here
      hostname: localhost
      port: 1414
      queue-manager: QMMSKT09
      channel: DEV.APP.SVRCONN
      #queue-name: DEV.QUEUE.1