resources:
  some-system:
    ibm.mq:
      hostname: localhost
      port: 1414
      queue-manager: QMMSKT09
      channel: DEV.APP.SVRCONN
      #queue-name: DEV.QUEUE.1
    elasticsearch:
      hostname: localhost
      port: 9200
      cluster-name: docker-cluster
      index-name: csp-api-manager-events-index