version: "3.8"
services:
  # https://github.com/ibm-messaging/mq-container/blob/master/docs/developer-config.md
  ibmmq:
    image: ibmcom/mq:latest
    restart: unless-stopped
    ports:
      - 1414:1414
      - 9157:9157
      - 9443:9443
    environment:
      MQ_QMGR_NAME: QMMSKT09
      LICENSE: accept
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    restart: unless-stopped
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node