replicaCount: 1
image:
  name: "artifactory.raiffeisen.ru/csp-docker/temp/ping_pipe"
  tag: 3
ports:
  jmxJavaPort: 5555
  jmxPrometheusPort: 9404
apm:
  service_name: "153-csp-deals-qort-service"
  environment: "preview"
  server_urls: "http://s-msk-v-elk-apm.raiffeisen.ru:8200"
ingress:
  path: /csp-api-manager/?(.*)