apiVersion: v1
kind: ConfigMap
metadata:
  name: csp-api-application-config
data:
  application-dev.yml: |-
    spring:
      config:
        import: queues-dev.yml

    application:
      camel:
        demo-routes-autostartup: false

    resources:
      ibm.mq.fis:
        hostname: s-msk-t-imq011.raiffeisen.ru
        port: 1414
        queue-manager: QMMSKT03
        channel: CSP.MSKT03
      ibm.mq.nrlms:
        hostname: s-msk-t-imq011.raiffeisen.ru
        port: 1414
        queue-manager: QMMSKT03
        channel: NRLMS.MSKT03

      kafka:
        brokers: s-msk-v-elk-mq1.raiffeisen.ru:9092,s-msk-v-elk-mq2.raiffeisen.ru:9092,s-msk-v-elk-mq3.raiffeisen.ru:9092
        topicName: elk-v-core-services

      activemq:
        broker-url: tcp://active-mq.active-mq.svc.s-msk-d-csp-k8s.local:61616

    