apiVersion: v1
kind: ConfigMap
metadata:
  name: csp-api-application-config
data:
  application.yaml: |-
    resources:
      some-system:
        ibm.mq:
          hostname: localhost
          port: 1414
          queue-manager: QMMSKT09
          channel: DEV.APP.SVRCONN
          #queue-name: DEV.QUEUE.1

    