apiVersion: v1
kind: ConfigMap
metadata:
  name: csp-api-queues-config
data:
  queues-dev.yml: |-
    queues:
      fis-csp-nrlms: [INT.FIS.CSP.REQ, INT.CSP.NRLMS.REQ]
      nrlms-csp-fis: [INT.CSP.NRLMS.RESP, INT.FIS.CSP.RESP]

      factoring-csp-factoring_proxied-create_deal: [INT.FACTORING.CSP.CREATEFACTORINGDEAL.REQ, INT.FACTORING.CSP.CREATEFACTORINGDEAL.REQ.PROXIED]
      factoring-csp-factoring_proxied-change_close_date: [INT.FACTORING.CSP.CHANGEFACTORINGDEALCLOSEDATE.REQ, INT.FACTORING.CSP.CHANGEFACTORINGDEALCLOSEDATE.REQ.PROXIED]
      factoring-csp-factoring_proxied-create_rep: [INT.FACTORING.CSP.CREATEFACTORINGREPAYMENT.REQ, INT.FACTORING.CSP.CREATEFACTORINGREPAYMENT.REQ.PROXIED]

      factoring_proxied-csp-factoring-create_deal: [INT.FACTORING.CSP.CREATEFACTORINGDEAL.RESP.PROXIED, INT.FACTORING.CSP.CREATEFACTORINGDEAL.RESP]
      factoring_proxied-csp-factoring-change_close_date: [INT.FACTORING.CSP.CHANGEFACTORINGDEALCLOSEDATE.RESP.PROXIED, INT.FACTORING.CSP.CHANGEFACTORINGDEALCLOSEDATE.RESP]
      factoring_proxied-csp-factoring-create_rep: [INT.FACTORING.CSP.CREATEFACTORINGREPAYMENT.RESP.PROXIED, INT.FACTORING.CSP.CREATEFACTORINGREPAYMENT.RESP]

      factoring_proxied-csp-factoring-create_deal_err: [INT.FACTORING.CSP.CREATEFACTORINGDEAL.ERR.PROXIED, INT.FACTORING.CSP.CREATEFACTORINGDEAL.ERR]
      factoring_proxied-csp-factoring-change_close_date_err: [INT.FACTORING.CSP.CHANGEFACTORINGDEALCLOSEDATE.ERR.PROXIED, INT.FACTORING.CSP.CHANGEFACTORINGDEALCLOSEDATE.ERR]
      factoring_proxied-csp-factoring-create_rep_err: [INT.FACTORING.CSP.CREATEFACTORINGREPAYMENT.ERR.PROXIED, INT.FACTORING.CSP.CREATEFACTORINGREPAYMENT.ERR]


    