---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    command: csp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        command: csp
    spec:
      initContainers:
        - name: init-apmagent
          image: "artifactory.raiffeisen.ru/csp-docker/openjdk/elastic-apm-agent:1.24.0"
          volumeMounts: 
            - name: elastic-apm-agent
              mountPath: /elastic/apm/agent 
          command: ['cp', '-v', '/opt/workdir/elastic-apm-agent.jar', '/elastic/apm/agent']
        - name: init-jmx-exporter
          image: "artifactory.raiffeisen.ru/csp-docker/openjdk/openjdk-11.0.8-jre-slim-jmx:0.15.0"
          volumeMounts: 
            - name: jmx-exporter
              mountPath: /jmx-exporter 
          command: ['cp', '-v', '/opt/workdir/jmx_prometheus_javaagent.jar', '/jmx-exporter']  
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          command: ["java"]
          args:
            - "-Dcom.sun.management.jmxremote=true"
            - "-Dcom.sun.management.jmxremote.port={{ .Values.ports.jmxJavaPort }}"
            - "-Dcom.sun.management.jmxremote.authenticate=false"
            - "-Dcom.sun.management.jmxremote.ssl=false"
            - "-Delastic.apm.service_name={{ .Values.apm.service_name }}"
            - "-Delastic.apm.environment={{ .Values.apm.environment }}"
            - "-Delastic.apm.application_packages=com.example.restservice"
            - "-Delastic.apm.server_urls={{ .Values.apm.server_urls }}"
            - "-javaagent:/jmx-exporter/jmx_prometheus_javaagent.jar={{ .Values.ports.jmxPrometheusPort }}:/jmx-exporter/jmx_exporter_config.yaml"
            - "-javaagent:/elastic/apm/agent/elastic-apm-agent.jar"
            - "-jar"
            - "csp-api-manager.jar"
            - "--spring.config.import=file:///csp-api-manager/application.yaml"
          ports:
          - name: http
            containerPort: 8080
          - name: tcp-prometheus
            containerPort: {{ .Values.ports.jmxPrometheusPort }}
          volumeMounts:
            - name: jmx-exporter-config
              mountPath: "/jmx-exporter/jmx_exporter_config.yaml"
              subPath: jmx_exporter_config.yaml
            - name: application-config
              mountPath: "/csp-api-manager/application.yaml"
              subPath: application.yaml
            - name: elastic-apm-agent
              mountPath: /elastic/apm/agent
            - name: jmx-exporter
              mountPath: /jmx-exporter
          resources:
            requests:
              memory: 500Mi
              cpu: 200m
            limits:
              memory: 5000Mi
              cpu: 400m
      volumes:
        - name: jmx-exporter-config
          configMap:
            name: jmx-exporter-config
        - name: application-config
          configMap:
            name: application-config
        - name: elastic-apm-agent 
          emptyDir: {}
        - name: jmx-exporter
          emptyDir: {} 