---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
  - name: {{ .Chart.Name }}
    port: 80
    targetPort: 8080
  selector:
    app: {{ .Chart.Name }}